### ISSUE TITLE
Default `grunt` task not building project properly

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-example-full-stack#54] opened 2015-02-17 05:01 UTC
Running `grunt` produces:

```
...
Running "build-lbclient" task
Fatal error: ENOTDIR, stat '/Users/sh/work-repos/loopback-example-full-stack/node_modules/loopback-boot/node_modules/instructions.json/package.json'
```
@bajtos Any ideas?

**Comment by bajtos** [comment] 2015-02-17 18:31
Nope. Do you have a full stack-trace?

**Comment by superkhau** [comment] 2015-02-18 01:29
Might be related to https://github.com/strongloop/loopback-boot/issues/94

**Comment by andrenventer** [comment] 2015-02-18 05:59
Did you add that file to the root? Did you get a clean main branch build
working?

Andre

**Comment by superkhau** [comment] 2015-02-18 07:27
@andrenventer Can you paste the stack trace you sent in the email here so @bajtos can take a look?

**Comment by andrenventer** [comment] 2015-02-18 07:29
cd Projects/loopback-example-full-stack/

nomad@Nomads-MacBook-Pro-2 ~/P/loopback-example-full-stack> npm install

npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current:
{"node":"1.0.4","npm":"2.3.0"})



> fsevents@0.3.5 install
/Users/nomad/Projects/loopback-example-full-stack/node_modules/karma/node_modules/chokidar/node_modules/fsevents

> node-gyp rebuild


child_process: customFds option is deprecated, use stdio instead.

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer
directory '/Library/Developer/CommandLineTools' is a command line tools
instance


xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer
directory '/Library/Developer/CommandLineTools' is a command line tools
instance


  SOLINK_MODULE(target) Release/.node

  SOLINK_MODULE(target) Release/.node: Finished

  CXX(target) Release/obj.target/fse/fsevents.o

  SOLINK_MODULE(target) Release/fse.node

  SOLINK_MODULE(target) Release/fse.node: Finished



> phantomjs@1.9.15 install
/Users/nomad/Projects/loopback-example-full-stack/node_modules/karma-phantomjs-launcher/node_modules/phantomjs

> node install.js


Download already available at
/var/folders/4z/8w2597v51qdgd0zp9rvxp9jr0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip

Extracting zip contents

Removing
/Users/nomad/Projects/loopback-example-full-stack/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom

Copying extracted folder
/var/folders/4z/8w2597v51qdgd0zp9rvxp9jr0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1424148602793/phantomjs-1.9.8-macosx
->
/Users/nomad/Projects/loopback-example-full-stack/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom

Writing location.js file

Done. Phantomjs binary available at
/Users/nomad/Projects/loopback-example-full-stack/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs



> gifsicle@1.0.3 postinstall
/Users/nomad/Projects/loopback-example-full-stack/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle

> node lib/install.js


     fetch :
https://raw.github.com/imagemin/gifsicle-bin/v1.0.3/vendor/osx/gifsicle

  progress : [====================] 100% 0.0s


✔ pre-build test passed successfully!

npm WARN engine async-listener@0.4.7: wanted: {"node":"<=0.11.8"} (current:
{"node":"1.0.4","npm":"2.3.0"})



> jpegtran-bin@1.0.2 postinstall
/Users/nomad/Projects/loopback-example-full-stack/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin

> node lib/install.js


     fetch :
https://raw.github.com/imagemin/jpegtran-bin/v1.0.2/vendor/osx/jpegtran

  progress : [====================] 100% 0.0s


✔ pre-build test passed successfully!


> optipng-bin@1.0.1 postinstall
/Users/nomad/Projects/loopback-example-full-stack/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin

> node lib/install.js


     fetch :
https://raw.github.com/imagemin/optipng-bin/v1.0.1/vendor/osx/optipng

  progress : [====================] 100% 0.0s


✔ pre-build test passed successfully!


> pngquant-bin@1.0.1 postinstall
/Users/nomad/Projects/loopback-example-full-stack/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin

> node lib/install.js


     fetch :
https://raw.github.com/imagemin/pngquant-bin/v1.0.1/vendor/osx/pngquant

  progress : [====================] 100% 0.0s


✔ pre-build test passed successfully!


> kerberos@0.0.9 install
/Users/nomad/Projects/loopback-example-full-stack/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos

> (node-gyp rebuild 2> builderror.log) || (exit 0)


  CXX(target) Release/obj.target/kerberos/lib/kerberos.o

  CXX(target) Release/obj.target/kerberos/lib/worker.o

  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o

  CC(target) Release/obj.target/kerberos/lib/base64.o

  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o

  SOLINK_MODULE(target) Release/kerberos.node

  SOLINK_MODULE(target) Release/kerberos.node: Finished


> bson@0.2.19 install
/Users/nomad/Projects/loopback-example-full-stack/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson

> (node-gyp rebuild 2> builderror.log) || (exit 0)


  CXX(target) Release/obj.target/bson/ext/bson.o

  SOLINK_MODULE(target) Release/bson.node

  SOLINK_MODULE(target) Release/bson.node: Finished


> ws@0.4.32 install
/Users/nomad/Projects/loopback-example-full-stack/node_modules/karma/node_modules/
socket.io/node_modules/socket.io-client/node_modules/ws

> (node-gyp rebuild 2> builderror.log) || (exit 0)


  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

karma-chrome-launcher@0.1.7 node_modules/karma-chrome-launcher


grunt-contrib-copy@0.5.0 node_modules/grunt-contrib-copy


connect-livereload@0.4.1 node_modules/connect-livereload


karma-jasmine@0.1.5 node_modules/karma-jasmine


async@0.9.0 node_modules/async


grunt-contrib-clean@0.5.0 node_modules/grunt-contrib-clean

└── rimraf@2.2.8


grunt-concurrent@0.5.0 node_modules/grunt-concurrent

├── pad-stdio@0.1.1 (lpad@0.2.1)

└── async@0.2.10


grunt-filerev@0.2.1 node_modules/grunt-filerev

├── each-async@0.1.3

└── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)


grunt-newer@0.7.0 node_modules/grunt-newer

├── rimraf@2.2.6

└── async@0.2.10


time-grunt@0.4.0 node_modules/time-grunt

├── date-time@0.1.1

├── figures@1.3.5

├── text-table@0.2.0

├── pretty-ms@0.2.2 (parse-ms@0.1.2)

├── hooker@0.2.3

└── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0,
supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)


jshint-stylish@0.4.0 node_modules/jshint-stylish

├── log-symbols@1.0.1

├── text-table@0.2.0

└── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0,
supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)


compression@1.4.1 node_modules/compression

├── vary@1.0.0

├── on-headers@1.0.0

├── bytes@1.0.0

├── debug@2.1.1 (ms@0.6.2)

├── compressible@2.0.2 (mime-db@1.7.0)

└── accepts@1.2.4 (negotiator@0.5.1, mime-types@2.0.9)


errorhandler@1.3.4 node_modules/errorhandler

├── escape-html@1.0.1

└── accepts@1.2.4 (negotiator@0.5.1, mime-types@2.0.9)


grunt-contrib-concat@0.5.0 node_modules/grunt-contrib-concat

├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0,
supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)

└── source-map@0.1.43 (amdefine@0.1.0)


grunt-karma@0.8.3 node_modules/grunt-karma

└── lodash@2.4.1


grunt-usemin@2.6.2 node_modules/grunt-usemin

├── debug@2.1.1 (ms@0.6.2)

├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0,
supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)

└── lodash@2.4.1


grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch

├── async@0.2.10

├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3,
qs@0.5.6)

├── gaze@0.5.1 (globule@0.1.0)

└── lodash@2.4.1


karma-phantomjs-launcher@0.1.4 node_modules/karma-phantomjs-launcher

└── phantomjs@1.9.15 (which@1.0.8, progress@1.1.8, kew@0.4.0,
request-progress@0.3.1, fs-extra@0.16.3, adm-zip@0.4.4, npmconf@2.0.9,
request@2.42.0)


load-grunt-tasks@0.6.0 node_modules/load-grunt-tasks

├── multimatch@0.3.0 (array-differ@0.1.0, array-union@0.1.0, minimatch@0.3.0
)

└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)


grunt-contrib-htmlmin@0.3.0 node_modules/grunt-contrib-htmlmin

├── pretty-bytes@0.1.2

├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

└── html-minifier@0.6.9 (relateurl@0.2.6, change-case@2.1.6,
clean-css@2.2.23, cli@0.6.5, uglify-js@2.4.16)


grunt-contrib-connect@0.8.0 node_modules/grunt-contrib-connect

├── open@0.0.5

├── portscanner@0.2.3 (async@0.1.15)

└── connect@2.19.6 (parseurl@1.0.1, response-time@2.0.0, cookie@0.1.2,
escape-html@1.0.1, pause@0.0.1, cookie-signature@1.0.3, vhost@1.0.0,
fresh@0.2.2, qs@0.6.6, on-headers@0.0.0, basic-auth-connect@1.0.0,
bytes@1.0.0, serve-favicon@2.0.1, morgan@1.1.1, errorhandler@1.0.2,
cookie-parser@1.1.0, connect-timeout@1.1.0, method-override@2.0.2,
debug@1.0.2, body-parser@1.3.1, express-session@1.2.1, csurf@1.2.1,
type-is@1.2.1, compression@1.0.7, serve-static@1.2.3, multiparty@3.2.8,
serve-index@1.1.1)


loopback-boot@2.6.4 node_modules/loopback-boot

├── commondir@0.0.1

├── toposort@0.2.10

├── debug@2.1.1 (ms@0.6.2)

├── semver@4.3.0

└── lodash@2.4.1


grunt@0.4.5 node_modules/grunt

├── which@1.0.8

├── dateformat@1.0.2-1.2.3

├── eventemitter2@0.4.14

├── getobject@0.1.0

├── rimraf@2.2.8

├── colors@0.6.2

├── async@0.1.22

├── grunt-legacy-util@0.2.0

├── hooker@0.2.3

├── nopt@1.0.10 (abbrev@1.0.5)

├── exit@0.1.2

├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)

├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)

├── lodash@0.9.2

├── coffee-script@1.3.3

├── underscore.string@2.2.1

├── iconv-lite@0.2.11

├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)

├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)

└── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)


loopback-datasource-juggler@2.17.0 node_modules/loopback-datasource-juggler

├── inflection@1.6.0

├── qs@2.3.3

├── loopback-connector@1.2.1

├── debug@2.1.1 (ms@0.6.2)

└── traverse@0.6.6


grunt-svgmin@0.4.0 node_modules/grunt-svgmin

├── each-async@0.1.3

├── pretty-bytes@0.1.2

├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

└── svgo@0.4.5 (colors@0.6.2, whet.extend@0.9.9, coa@0.4.1, sax@0.6.1,
js-yaml@2.1.3)


grunt-wiredep@1.9.0 node_modules/grunt-wiredep

└── wiredep@1.8.6 (propprop@0.3.0, minimist@1.1.0, chalk@0.5.1,
through2@0.6.3, glob@4.3.5, lodash@2.4.1, bower-config@0.5.2)


grunt-contrib-jshint@0.10.0 node_modules/grunt-contrib-jshint

├── hooker@0.2.3

└── jshint@2.5.11 (strip-json-comments@1.0.2, underscore@1.6.0, exit@0.1.2,
console-browserify@1.1.0, shelljs@0.3.0, minimatch@1.0.0, cli@0.6.5,
htmlparser2@3.8.2)


grunt-contrib-cssmin@0.10.0 node_modules/grunt-contrib-cssmin

├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

├── clean-css@2.2.23 (commander@2.2.0)

└── maxmin@0.2.2 (figures@1.3.5, pretty-bytes@0.1.2, chalk@0.5.1,
gzip-size@0.2.0)


grunt-contrib-uglify@0.5.1 node_modules/grunt-contrib-uglify

├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0,
supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)

├── lodash@2.4.1

├── uglify-js@2.4.16 (uglify-to-browserify@1.0.2, async@0.2.10,
optimist@0.3.7, source-map@0.1.34)

└── maxmin@0.2.2 (figures@1.3.5, pretty-bytes@0.1.2, gzip-size@0.2.0)


grunt-ng-annotate@0.8.0 node_modules/grunt-ng-annotate

└── ng-annotate@0.14.1 (tryor@0.1.2, alter@0.2.0, simple-fmt@0.1.0,
simple-is@0.2.0, stringset@0.2.1, stringmap@0.2.2, stable@0.1.5,
convert-source-map@0.4.1, ordered-ast-traverse@0.1.1, optimist@0.6.1,
source-map@0.1.43, esprima@1.2.4, acorn@0.9.0)


browserify@4.2.3 node_modules/browserify

├── https-browserify@0.0.0

├── tty-browserify@0.0.0

├── builtins@0.0.7

├── constants-browserify@0.0.1

├── path-browserify@0.0.0

├── process@0.7.0

├── os-browserify@0.1.2

├── inherits@2.0.1

├── commondir@0.0.1

├── stream-browserify@1.0.0

├── defined@0.0.0

├── stream-combiner@0.0.4

├── duplexer@0.1.1

├── shell-quote@0.0.1

├── domain-browser@1.1.4

├── xtend@3.0.0

├── shallow-copy@0.0.1

├── deep-equal@0.2.2

├── assert@1.1.2

├── querystring-es3@0.2.1

├── punycode@1.2.4

├── string_decoder@0.0.1

├── util@0.10.3

├── parents@0.0.3 (path-platform@0.0.1)

├── timers-browserify@1.3.0 (process@0.10.0)

├── vm-browserify@0.0.4 (indexof@0.0.1)

├── events@1.0.2

├── console-browserify@1.1.0 (date-now@0.1.4)

├── subarg@0.0.1 (minimist@0.0.10)

├── url@0.10.2 (punycode@1.3.2)

├── readable-stream@1.0.33 (isarray@0.0.1, string_decoder@0.10.31,
core-util-is@1.0.1)

├── http-browserify@1.7.0 (Base64@0.2.1)

├── through2@1.1.1 (xtend@4.0.0, readable-stream@1.1.13)

├── buffer@2.8.2 (ieee754@1.1.4, base64-js@0.0.7, is-array@1.0.1)

├── resolve@0.7.4

├── concat-stream@1.4.7 (typedarray@0.0.6, readable-stream@1.1.13)

├── glob@3.2.11 (minimatch@0.3.0)

├── JSONStream@0.8.4 (through@2.3.6, jsonparse@0.0.5)

├── deps-sort@0.1.2 (through@2.3.6, minimist@0.0.10, JSONStream@0.6.4)

├── browser-resolve@1.7.0 (resolve@1.1.0)

├── browser-pack@2.0.1 (through@2.3.6, combine-source-map@0.3.0,
JSONStream@0.6.4)

├── umd@2.1.0 (through@2.3.6, rfile@1.0.0, uglify-js@2.4.16, ruglify@1.0.0)

├── derequire@0.8.0 (estraverse@1.5.1, esrefactor@0.1.0,
esprima-fb@3001.1.0-dev-harmony-fb)

├── insert-module-globals@6.0.0 (process@0.6.0, through@2.3.6,
JSONStream@0.7.4, lexical-scope@1.1.0)

├── module-deps@2.1.5 (parents@0.0.2, minimist@0.0.10, stream-combiner@0.1.0,
through2@0.4.2, resolve@0.6.3, browser-resolve@1.2.4, duplexer2@0.0.2,
JSONStream@0.7.4, detective@3.1.0)

├── syntax-error@1.1.2 (acorn@0.9.0)

├── browserify-zlib@0.1.4 (pako@0.2.5)

└── crypto-browserify@2.1.10 (ripemd160@0.2.0, sha.js@2.1.6)


grunt-google-cdn@0.4.3 node_modules/grunt-google-cdn

├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0,
supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)

└── google-cdn@0.7.0 (regexp-quote@0.0.0, google-cdn-data@0.1.17,
debug@1.0.4, semver@2.3.2, cdnjs-cdn-data@0.1.1)


grunt-autoprefixer@0.8.2 node_modules/grunt-autoprefixer

├── diff@1.0.8

├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0,
supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)

└── autoprefixer@2.2.0 (fs-extra@0.10.0, postcss@2.1.2,
caniuse-db@1.0.30000071)


loopback@2.12.1 node_modules/loopback

├── sl-blip@1.0.0

├── uid2@0.0.3

├── nodemailer-stub-transport@0.1.5

├── stable@0.1.5

├── canonical-json@0.0.4

├── inflection@1.4.2

├── debug@2.0.0 (ms@0.6.2)

├── loopback-connector-remote@1.0.3

├── ejs@1.0.0

├── loopback-phase@1.2.0 (debug@2.1.1)

├── bcryptjs@2.0.2

├── serve-favicon@2.2.0 (ms@0.7.0, fresh@0.2.4, parseurl@1.3.0, etag@1.5.1)

├── continuation-local-storage@3.1.2 (emitter-listener@1.0.1,
async-listener@0.4.7)

├── body-parser@1.8.4 (media-typer@0.3.0, bytes@1.0.0, raw-body@1.3.0,
depd@0.4.5, qs@2.2.4, on-finished@2.1.0, type-is@1.5.7, iconv-lite@0.4.4)

├── underscore.string@2.3.3

├── express@4.11.2 (utils-merge@1.0.0, merge-descriptors@0.0.2,
methods@1.1.1, fresh@0.2.4, cookie@0.1.2, escape-html@1.0.1,
range-parser@1.0.2, cookie-signature@1.0.5, finalhandler@0.3.3, vary@1.0.0,
media-typer@0.3.0, parseurl@1.3.0, serve-static@1.8.1,
content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.0,
on-finished@2.2.0, qs@2.3.3, debug@2.1.1, etag@1.5.1, send@0.11.1,
accepts@1.2.4, type-is@1.5.7, proxy-addr@1.0.6)

├── nodemailer@1.3.0 (hyperquest@0.3.0, nodemailer-direct-transport@1.0.0,
nodemailer-smtp-transport@0.1.13, buildmail@1.2.0, libmime@0.1.7)

└── strong-remoting@2.12.1 (eventemitter2@0.4.14, browser-request@0.3.3,
qs@2.3.3, js2xmlparser@0.1.7, cors@2.5.3, traverse@0.6.6, jayson@1.1.3,
request@2.53.0, xml2js@0.4.5)


bower@1.3.12 node_modules/bower

├── is-root@1.0.0

├── junk@1.0.0

├── stringify-object@1.0.0

├── which@1.0.8

├── abbrev@1.0.5

├── chmodr@0.1.0

├── osenv@0.1.0

├── archy@0.0.2

├── opn@1.0.1

├── rimraf@2.2.8

├── lru-cache@2.5.0

├── bower-logger@0.2.2

├── bower-endpoint-parser@0.2.2

├── graceful-fs@3.0.5

├── lockfile@1.0.0

├── nopt@3.0.1

├── retry@0.6.0

├── tmp@0.0.23

├── request-progress@0.3.0 (throttleit@0.0.2)

├── q@1.0.1

├── chalk@0.5.0 (escape-string-regexp@1.0.2, ansi-styles@1.1.0,
supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)

├── shell-quote@1.4.2 (array-filter@0.0.1, array-reduce@0.0.0,
array-map@0.0.0, jsonify@0.0.0)

├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3
)

├── semver@2.3.2

├── p-throttler@0.1.0 (q@0.9.7)

├── fstream@1.0.4 (inherits@2.0.1)

├── mkdirp@0.5.0 (minimist@0.0.8)

├── promptly@0.2.0 (read@1.0.5)

├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)

├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)

├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)

├── decompress-zip@0.0.8 (nopt@2.2.1, mkpath@0.1.0, touch@0.0.2,
readable-stream@1.1.13, binary@0.3.0)

├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0,
aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.4.0,
tunnel-agent@0.4.0, qs@1.2.2, node-uuid@1.4.2, mime-types@1.0.2,
form-data@0.1.4, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1,
hawk@1.1.1)

├── glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)

├── bower-registry-client@0.2.3 (graceful-fs@2.0.3, request-replay@0.2.0,
lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)

├── cardinal@0.4.0 (redeyed@0.4.4)

├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2,
latest-version@0.2.0, configstore@0.3.2)

├── mout@0.9.1

├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)

├── inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6,
readline2@0.1.1, lodash@2.4.1, cli-color@0.3.2, rx@2.3.25)

└── insight@0.4.3 (object-assign@1.0.0, chalk@0.5.1, lodash.debounce@2.4.1,
os-name@1.0.3, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.0)


loopback-explorer@1.6.4 node_modules/loopback-explorer

├── debug@1.0.4 (ms@0.6.2)

├── cors@2.5.3 (vary@1.0.0)

├── lodash@2.4.1

├── express@3.19.2 (basic-auth@1.0.0, merge-descriptors@0.0.2,
utils-merge@1.0.0, methods@1.1.1, cookie@0.1.2, fresh@0.2.4,
escape-html@1.0.1, range-parser@1.0.2, cookie-signature@1.0.5, vary@1.0.0,
media-typer@0.3.0, parseurl@1.3.0, content-disposition@0.5.0,
commander@2.6.0, depd@1.0.0, debug@2.1.1, etag@1.5.1, proxy-addr@1.0.6,
send@0.11.1, mkdirp@0.5.0, connect@2.28.3)

└── swagger-ui@2.0.24 (coffee-script@1.6.3, handlebars@1.0.12,
swagger-client@2.0.36, less@1.4.2)


grunt-contrib-imagemin@0.8.1 node_modules/grunt-contrib-imagemin

├── pretty-bytes@1.0.3 (get-stdin@4.0.1)

├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0,
supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)

└── imagemin@1.0.5 (get-stdin@3.0.2, stat-mode@0.2.0, ware@0.3.0, nopt@3.0.1,
tempfile@1.1.0, fs-extra@0.11.1, imagemin-svgo@1.0.2,
imagemin-gifsicle@1.0.0, imagemin-jpegtran@1.0.0, imagemin-optipng@1.0.0,
imagemin-pngquant@1.0.2)


loopback-connector-mongodb@1.7.0 node_modules/loopback-connector-mongodb

├── loopback-connector@1.2.1

├── debug@2.1.1 (ms@0.6.2)

└── mongodb@2.0.16 (readable-stream@1.0.31, mongodb-core@1.1.12)


karma@0.12.31 node_modules/karma

├── di@0.0.1

├── graceful-fs@2.0.3

├── rimraf@2.2.8

├── colors@0.6.2

├── mime@1.2.11

├── q@0.9.7

├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)

├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)

├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)

├── source-map@0.1.43 (amdefine@0.1.0)

├── chokidar@0.12.6 (async-each@0.1.6, readdirp@1.3.0, fsevents@0.3.5)

├── log4js@0.6.22 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)

├── lodash@2.4.1

├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)

├── connect@2.26.6 (fresh@0.2.4, cookie@0.1.2, pause@0.0.1,
cookie-signature@1.0.5, response-time@2.0.1, vhost@3.0.0, on-headers@1.0.0,
basic-auth-connect@1.0.0, media-typer@0.3.0, bytes@1.0.0, parseurl@1.3.0,
depd@0.4.5, cookie-parser@1.3.4, connect-timeout@1.3.0, finalhandler@0.2.0,
qs@2.2.4, debug@2.0.0, method-override@2.2.0, morgan@1.3.2,
serve-favicon@2.1.7, csurf@1.6.6, type-is@1.5.7, express-session@1.8.2,
serve-static@1.6.5, multiparty@3.3.2, errorhandler@1.2.4, compression@1.1.2,
body-parser@1.8.4, serve-index@1.2.1)

├── useragent@2.0.10 (lru-cache@2.2.4)

└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3,
socket.io-client@0.9.16)

nomad@Nomads-MacBook-Pro-2 ~/P/loopback-example-full-stack> bower install

bower angular#~1.2.16           cached git://
github.com/angular/bower-angular.git#1.2.28

bower angular#~1.2.16         validate 1.2.28 against git://
github.com/angular/bower-angular.git#~1.2.16

bower json3#~3.3.1              cached git://
github.com/bestiejs/json3.git#3.3.2

bower json3#~3.3.1            validate 3.3.2 against git://
github.com/bestiejs/json3.git#~3.3.1

bower es5-shim#~3.1.0           cached git://
github.com/es-shims/es5-shim.git#3.1.1

bower es5-shim#~3.1.0         validate 3.1.1 against git://
github.com/es-shims/es5-shim.git#~3.1.0

bower angular-route#~1.2.16     cached git://
github.com/angular/bower-angular-route.git#1.2.28

bower angular-route#~1.2.16   validate 1.2.28 against git://
github.com/angular/bower-angular-route.git#~1.2.16

bower angular-mocks#~1.2.16     cached git://
github.com/angular/bower-angular-mocks.git#1.2.28

bower angular-mocks#~1.2.16   validate 1.2.28 against git://
github.com/angular/bower-angular-mocks.git#~1.2.16

bower angular-scenario#~1.2.16  cached git://
github.com/angular/bower-angular-scenario.git#1.2.28

bower angular-scenario#~1.2.16         validate 1.2.28 against git://
github.com/angular/bower-angular-scenario.git#~1.2.16

bower json3#~3.3.1                      install json3#3.3.2

bower es5-shim#~3.1.0                   install es5-shim#3.1.1

bower angular-mocks#~1.2.16             install angular-mocks#1.2.28

bower angular-route#~1.2.16             install angular-route#1.2.28

bower angular#~1.2.16                   install angular#1.2.28

bower angular-scenario#~1.2.16          install angular-scenario#1.2.28


json3#3.3.2 bower_components/json3


es5-shim#3.1.1 bower_components/es5-shim


angular-mocks#1.2.28 bower_components/angular-mocks

└── angular#1.2.28


angular-route#1.2.28 bower_components/angular-route

└── angular#1.2.28


angular#1.2.28 bower_components/angular


angular-scenario#1.2.28 bower_components/angular-scenario

└── angular#1.2.28

nomad@Nomads-MacBook-Pro-2 ~/P/loopback-example-full-stack> grunt serve

Running "serve" task


Running "clean:server" (clean) task


Running "build-lbclient" task

Fatal error: ENOTDIR, stat
'/Users/nomad/Projects/loopback-example-full-stack/node_modules/loopback-boot/node_modules/instructions.json/package.json'



Execution Time (2015-02-17 04:51:27 UTC)

loading tasks    3ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 10%

serve            2ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 7%

clean:server     5ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 17%

**Comment by superkhau** [comment] 2015-02-18 07:31
@andrenventer ty :bow: 
@bajtos stack trace :point_up:

**Comment by bajtos** [comment] 2015-02-18 08:03
This is indeed a duplicate of strongloop/loopback-boot#94. Depending on the resolution of https://github.com/strongloop/loopback-boot/pull/95, we may need to upgrade to browserify 5.x in this project.

**Comment by bajtos** [comment] 2015-03-30 13:23
This issue should be fixed now, please update your dependencies to get `loopback-boot@2.6.5` or newer.

**Closed by bajtos** 2015-03-30 13:23 UTC
Labels: bug
